"""empty message

Revision ID: 9335ca0771f7
Revises: 
Create Date: 2024-08-26 14:00:28.503639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9335ca0771f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_spent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scrolled_to_bottom', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_column('scrolled_to_bottom')
        batch_op.drop_column('time_spent')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
